config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :comments, :only => [:create, :destroy, :show] do
    get 'upvote', to: 'comments#upvote', as: :upvote
    get 'downvote', to: 'comments#downvote', as: :downvote
    get 'reply', to: "comments#reply", as: :reply
  end

  get '/r/:community', to: 'posts#index', as: :community_by_name
  get '/r/:community/:id', to: 'posts#show', as: :post_by_title

  resources :communities do
    resources :community_users
    get 'subscribe', to: 'communities#subscribe', as: :subscribe
  end

  resources :posts do
    resources :post_votes
    get 'upvote', to: 'posts#upvote', as: :upvote
    get 'downvote', to: 'posts#downvote', as: :downvote
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  acts_as_votable

  # add a like for the creator of the comment
  after_save 'self.liked_by self.user'

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end

  def total_votes
    self.get_upvotes.size - self.get_downvotes.size
  end

  # Upvotes for the current user, or removes vote if already upvoted
  def upvote(current_user)
    if current_user && current_user.voted_up_on?(self)
      self.unliked_by current_user
    else
      self.liked_by current_user
    end
  end

  # Downvotes for the current user, or removes vote if already downvoted
  def downvote(current_user)
    if current_user && current_user.voted_down_on?(self)
      self.undisliked_by current_user
    else
      self.downvote_by current_user
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment_hash = params[:comment]
    @obj = @comment_hash[:commentable_type].constantize.find(@comment_hash[:commentable_id])
    @comment = Comment.build_from(@obj, current_user.id, @comment_hash[:body])
    if @comment.save
      render :partial => "comments/comment", :locals => { :comment => @comment }, :layout => false, :status => :created
    else
      render :js => "alert('error saving comment');"
    end
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :json => @comment, :status => :ok
    else
      render :js => "alert('error deleting comment');"
    end
  end

  def upvote
    @comment = Comment.find params[:comment_id]
    @comment.upvote current_user
    render :show
  end

  def downvote
    @comment = Comment.find params[:comment_id]
    @comment.downvote current_user
    render :show
  end

  def reply
    @comment = Comment.find params[:comment_id]
    respond_with @comment
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%div.comment{ :id => "comment-#{comment.id}" }
  .row
    .col-sm-1.comment-vote
      .row
        = upvote_button(comment_upvote_path(comment), comment, current_user, "comment")
      .row
        %span.votes{:id => "comment-count-"+comment.id.to_s}= comment.total_votes
      .row
        = downvote_button(comment_downvote_path(comment), comment, current_user, "comment")

    .col-sm-9.comment-content
      %hr
      - if current_user && current_user.id == comment.user_id
        = link_to "×", comment_path(comment), :method => :delete, :remote => true,
        :confirm => "Are you sure you want to remove this comment?", :disable_with => "×", :class => 'close'
      %h4
        = comment.user.email
        %small= time_ago_in_words comment.updated_at
      %p= comment.body

      - if current_user
        = link_to "Reply", comment_reply_path(comment), :remote => true, class: "comment-reply"

      = if comment.has_children?
        = render :partial => 'comments/comment', :collection => comment.children, :as => :comment

app/views/comments/_form.html.haml
.row
  .comment-form
    = simple_form_for comment, :remote => true do |f|
      = f.input :body, :input_html => { :rows => "2" }, :label => false
      = f.input :commentable_id, :as => :hidden, :value => comment.commentable_id
      = f.input :commentable_type, :as => :hidden, :value => comment.commentable_type
      = f.button :submit, :class => "btn btn-primary", :disable_with => "Submitting…"

app/views/comments/reply.js.erb
var form = '<%=
    escape_javascript(
        render :partial => 'comments/form', :locals => { :comment => Comment.new }
    )
 %>';
$(" #comment-<%= @comment.id.to_s %> .comment-content ").append(form);

app/views/comments/show.js.erb
$("#comment-count-<%= @comment.id.to_s %>")
        .html('<%= @comment.get_upvotes.size - @comment.get_downvotes.size %>');
$('#comment-upvote-<%= @comment.id.to_s %>')
        .attr('class', '<%= upvote_class(@comment, current_user) %>');
$('#comment-downvote-<%= @comment.id.to_s %>')
        .attr('class', '<%= downvote_class(@comment, current_user) %>');