config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :comments, :only => [:create, :destroy, :show] do
    get 'upvote', to: 'comments#upvote', as: :upvote
    get 'downvote', to: 'comments#downvote', as: :downvote
    get 'reply', to: "comments#reply", as: :reply
  end

  get '/r/:community', to: 'posts#index', as: :community_by_name
  get '/r/:community/:id', to: 'posts#show', as: :post_by_title

  resources :communities do
    resources :community_users
    get 'subscribe', to: 'communities#subscribe', as: :subscribe
  end

  resources :posts do
    resources :post_votes
    get 'upvote', to: 'posts#upvote', as: :upvote
    get 'downvote', to: 'posts#downvote', as: :downvote
  end

  root 'posts#index'

end

app/models/community_user.rb
class CommunityUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :community
end

app/controllers/community_users_controller.rb
class CommunityUsersController < ApplicationController
  before_action :set_community_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:  [:destroy, :new, :edit]
  respond_to :html

  def index
    @community_users = CommunityUser.all
    respond_with(@community_users)
  end

  def show
    respond_with(@community_user)
  end

  def new
    @community_user = CommunityUser.new
    respond_with(@community_user)
  end

  def edit
  end

  def create
    community = Community.find_by_name(params[:community_id])
    @community_user = community.community_users.new
    @community_user.user = current_user
    @community_user.save
    redirect_to community_by_name_path(community)
  end

  def update
    community = Community.find_by_name(params[:community_id])
    @community_user.update(community_user_params)
    redirect_to community_by_name_path(community)
  end

  def destroy
    @community_user.destroy
    respond_with(@community_user)
  end

  private
    def set_community_user
      @community_user = CommunityUser.find(params[:id])
    end

    def community_user_params
      params.require(:community_user).permit(:user_id, :community_id, :subscriber)
    end
end

app/helpers/community_users_helper.rb
module CommunityUsersHelper
end

app/views/community_users/_form.html.haml
= form_for [@community, @community_user] do |f|
  .field
    = f.check_box :subscriber
    = f.label :subscriber, "Subscribed"
  .actions
    = f.submit "Update Subscription", class: "btn btn-default"

app/views/community_users/edit.html.erb
<h1>Editing community_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @community_user %> |
<%= link_to 'Back', community_users_path %>

app/views/community_users/index.html.erb
<h1>Listing community_users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Community</th>
      <th>Admin</th>
      <th>Subscriber</th>
      <th>Banned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @community_users.each do |community_user| %>
      <tr>
        <td><%= community_user.user %></td>
        <td><%= community_user.community %></td>
        <td><%= community_user.admin %></td>
        <td><%= community_user.subscriber %></td>
        <td><%= community_user.banned %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/community_users/new.html.erb
<h1>New community_user</h1>

<%= render 'form' %>

<%= link_to 'Back', community_users_path %>

app/views/community_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @community_user.user %>
</p>

<p>
  <strong>Community:</strong>
  <%= @community_user.community %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @community_user.admin %>
</p>

<p>
  <strong>Subscriber:</strong>
  <%= @community_user.subscriber %>
</p>

<p>
  <strong>Banned:</strong>
  <%= @community_user.banned %>
</p>

<%= link_to 'Edit', edit_community_user_path(@community_user) %> |
<%= link_to 'Back', community_users_path %>