config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :comments, :only => [:create, :destroy, :show] do
    get 'upvote', to: 'comments#upvote', as: :upvote
    get 'downvote', to: 'comments#downvote', as: :downvote
    get 'reply', to: "comments#reply", as: :reply
  end

  get '/r/:community', to: 'posts#index', as: :community_by_name
  get '/r/:community/:id', to: 'posts#show', as: :post_by_title

  resources :communities do
    resources :community_users
    get 'subscribe', to: 'communities#subscribe', as: :subscribe
  end

  resources :posts do
    resources :post_votes
    get 'upvote', to: 'posts#upvote', as: :upvote
    get 'downvote', to: 'posts#downvote', as: :downvote
  end

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :community
  has_many :comments
  acts_as_votable
  acts_as_commentable

  validates :community, presence: true
  validates :title,
            presence: true,
            length: { maximum: 128 }

  max_paginates_per 20

  # add a like for the creator of the post
  after_save 'self.liked_by self.user'

  # gets the net votes for the post
  def total_votes
    self.get_upvotes.size - self.get_downvotes.size
  end

  # Upvotes for the current user, or removes vote if already upvoted
  def upvote(current_user)
    if current_user && current_user.voted_up_on?(self)
      self.unliked_by current_user
    else
      self.liked_by current_user
    end
  end

  # Downvotes for the current user, or removes vote if already downvoted
  def downvote(current_user)
    if current_user && current_user.voted_down_on?(self)
      self.undisliked_by current_user
    else
      self.downvote_by current_user
    end
  end

  # gets the posts that belong to a community the user subscribes to
  def self.subscriptions(user)
    if user
      (Post.joins(:community)
          .where(communities: {default: true}) +
       Post.joins('INNER JOIN community_users ON posts.community_id = community_users.community_id')
          .where(community_users: {user_id: user.id, subscriber: true}) -
       Post.joins('INNER JOIN community_users ON posts.community_id = community_users.community_id')
          .where(community_users: {user_id: user.id, subscriber: false})
      ).uniq
    else
      Post.joins(:community)
          .where(communities: {default: true})
    end
  end

  def self.sort(posts, sortby)
    if sortby == 'new'
      posts.to_a.sort_by! { |post| post.created_at }
    else
      posts.to_a.sort_by! { |post| post.total_votes }
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:  [:destroy, :new, :edit]
  respond_to :html, :js, :json

  # GET /posts
  # GET /posts.json
  def index
    # viewing a specific community's posts
    if params[:community]
      @community = Community.find_by_name(params[:community])
      @posts =  @community.posts
    # viewing the main page
    else
      @posts = Post.subscriptions(current_user)
    end

    # sort and paginate the results
    @posts = Post.sort(@posts, params[:sortby])
    @posts = Kaminari.paginate_array(@posts.reverse).page params[:page]
    respond_with @posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # get all the root comments, ones that are the start of a thread
    @comments = @post.root_comments.order('created_at desc')

    if current_user
      @comment = Comment.build_from(@post, current_user.id, "")
      @community_user = current_user.communities.new
    end

    @community = @post.community
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save
    respond_with @post
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find params[:post_id]
    @post.upvote current_user
    redirect_to post_path(@post, format: :js)
  end

  def downvote
    @post = Post.find params[:post_id]
    @post.downvote current_user
    redirect_to post_path(@post, format: :js)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      if params[:community]
        @community = Community.find_by_name(params[:community])
        @posts =  @community.posts
        if @community.community_users.empty?
          @community_user = @community.community_users.new
        else
          @community_user = @community.community_users.last
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:id, :title, :url, :text, :community_id, :sortby)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def comments_link(post)
    link_to post.comment_threads.size.to_s + " comment".pluralize(post.comment_threads.size), post_by_title_path(post.community, post)
  end
end

app/views/posts/_form.html.haml
= simple_form_for [@community, @post] do |f|
  = f.label "Community"
  = f.collection_select :community_id, Community.all, :id, :name, {include_blank: true}, class: 'form-control combobox'
  = f.input :title
  = f.input :url
  = f.input :text, as: :text
  = f.button :submit

app/views/posts/_post.html.haml
.row
  .col-sm-1.post-vote
    .row
      = upvote_button(post_upvote_path(post), post, current_user, "post")
    .row
      %span.votes{:id => "post-count-"+post.id.to_s}= post.total_votes
    .row
      = downvote_button(post_downvote_path(post), post, current_user, "post")
  .col-sm-8
    .row
      = link_to post.title, post.url
    .row
      = 'Posted ' + time_ago_in_words(post.created_at) + ' by ' + post.user.email + ' to '
      = link_to post.community.name, community_by_name_path(post.community)
      %br
      = comments_link post
      - if current_user && current_user.id == post.user.id
        |
        = link_to 'Edit', edit_post_path(post)
        |
        = link_to 'Delete', post , method: :delete, data: { confirm: 'Are you sure?' }
      %hr

app/views/posts/_sidebar.html.haml
.row
  .btn-group-vertical
    = link_to 'Submit a New Post', new_post_path, class: "btn btn-primary"
    = link_to 'Create a New Community', new_community_path, class: "btn btn-default"

- if current_user && @community
  .row
    %hr
    = subscribe_button(current_user, @community)

-if @community
  %hr
  .row
    = @community.description

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form'
%hr
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.row
  .col-sm-10
    .row
      %ol.breadcrumb.col-sm-3
        %li= link_to "Top Posts", sortby: 'votes'
        %li= link_to "Newest Posts", sortby: 'new'
    .row
      - if @posts.empty?
        .panel.panel-default
          .panel-body No posts here!
      = render @posts

  .col-sm-2
    = render 'sidebar'

.row
  .col-sm-12
    = paginate @posts

app/views/posts/new.html.haml
%h1 New Post
= render 'form'
%hr
= link_to 'Back', posts_path

app/views/posts/show.html.haml
.row
  %p#notice= notice

.row
  = render @post

.row
  %h4 Comments:

- if current_user
  .row
    .col-sm-8
      = render :partial => 'comments/form', :locals => { :comment => @comment }
.row
  .col-sm-12#comments
    = render :partial => 'comments/comment', :collection => @comments, :as => :comment

app/views/posts/show.js.erb
$('#post-count-<%= @post.id.to_s %>').html('<%= @post.get_upvotes.size - @post.get_downvotes.size %>');
$('#post-upvote-<%= @post.id.to_s %>').attr('class', '<%= upvote_class(@post, current_user) %>');
$('#post-downvote-<%= @post.id.to_s %>').attr('class', '<%= downvote_class(@post, current_user) %>');