config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :comments, :only => [:create, :destroy, :show] do
    get 'upvote', to: 'comments#upvote', as: :upvote
    get 'downvote', to: 'comments#downvote', as: :downvote
    get 'reply', to: "comments#reply", as: :reply
  end

  get '/r/:community', to: 'posts#index', as: :community_by_name
  get '/r/:community/:id', to: 'posts#show', as: :post_by_title

  resources :communities do
    resources :community_users
    get 'subscribe', to: 'communities#subscribe', as: :subscribe
  end

  resources :posts do
    resources :post_votes
    get 'upvote', to: 'posts#upvote', as: :upvote
    get 'downvote', to: 'posts#downvote', as: :downvote
  end

  root 'posts#index'

end

app/models/community.rb
class Community < ActiveRecord::Base
  has_many :posts
  has_many :community_users
  has_many :users, through: :community_users

  validates :name,
            presence: true,
            length: { in: 3..32 }

  validates :description,
            presence: true,
            length: { maximum: 256 }

  def to_param
    name
  end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:  [:destroy, :new, :edit]
  respond_to :html

  def index
    @communities = Community.all
    respond_with(@communities)
  end

  def show
    respond_with(@community)
  end

  def new
    @community = Community.new
    respond_with(@community)
  end

  def edit
  end

  def create
    @community = Community.new(community_params)
    if @community.save
      redirect_to community_by_name_path(@community.name), notice: 'Community successfully created.'
    else
      render :new
    end

  end

  def update
    @community.update(community_params)
    respond_with(@community)
  end

  def destroy
    @community.destroy
    respond_with(@community)
  end

  def subscribe
    @community = Community.find_by_name(params[:community_id])
    current_user.update_subscription @community
    redirect_to community_by_name_path(@community.name)
  end

  private
    def set_community
      @community = Community.find_by_name(params[:id])
    end

    def community_params
      params.require(:community).permit(:name, :private, :description)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
  def subscribe_class(current_user, community)
    if current_user.subscribed? community
      "btn btn-primary btn-block"
    else
      "btn btn-default btn-block"
    end
  end

  def subscribe_text(current_user, community)
    if current_user.subscribed? community
      "Unsubscribe"
    else
      "Subscribe"
    end
  end

  def subscribe_button(current_user, community)
    link_to subscribe_text(current_user, community), community_subscribe_path(community), class: subscribe_class(current_user, community)
  end
end

app/views/communities/_form.html.haml
= simple_form_for @community do |f|
  = f.input :name
  = f.input :description, as: :text
  = f.button :submit, "Create"

app/views/communities/edit.html.erb
<h1>Editing community</h1>

<%= render 'form' %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<h1>Listing communities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Private</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @communities.each do |community| %>
      <tr>
        <td><%= community.name %></td>
        <td><%= community.private %></td>
        <td><%= link_to 'Show', community %></td>
        <td><%= link_to 'Edit', edit_community_path(community) %></td>
        <td><%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Community', new_community_path %>

app/views/communities/new.html.haml
%h1 Create a New Community
= render 'form'
%hr
= link_to 'Back', posts_path

app/views/communities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @community.name %>
</p>

<p>
  <strong>Private:</strong>
  <%= @community.private %>
</p>

<%= link_to 'Edit', edit_community_path(@community) %> |
<%= link_to 'Back', communities_path %>